### ISSUE TITLE
Craft in a subfolder

### ISSUE THREAD

**Issue by Gawel91** [moetelo/twiggy#40]
So it looks like the plugin throws an error (looking in the extension output) if Craft CMS is installed in a subfolder. I don't see on option to change this.

`Fatal error: Uncaught Error: Failed opening required '/Users/xxx/Workspace/projectname/bootstrap.php' (include_path='.:/opt/homebrew/Cellar/php/8.3.7/share/php/pear') in /Users/xxx/.vscode/extensions/moetelo.twiggy-0.15.0/dist/phpUtils/printCraftTwigEnvironment:16`

**Comment by moetelo** [comment]
Looks like some magic to resolve the root of the application needs to be applied here.

For now, is there any workaround for it?

For example, you could add that subfolder into the VS Code separately (File -> Add folder to Workspace...) or even open it in a separate VS Code instance.

**Comment by Gawel91** [comment]
Looks like it works when opening the folder in a separate VS Code instance but it's not convenient since the git folder is placed "above" the root of the application.

**Comment by Gawel91** [comment]
Would it be possible to add a scan functionality or a setting to the extension to provide the Craft location?

**Comment by moetelo** [comment]
Yes, I'm looking forward to implement project scanning.

Let's start with this one, keeping scanning in mind: #56

**Comment by foxtrotcz** [comment]
I just tried clean install of Craft in subfolder. I get this error:

```
Node.js v20.18.1
[Error - 8:31:53 PM] Server process exited with code 1.
[Info  - 8:31:53 PM] Connection to server got closed. Server will restart.
true
[Error - 8:31:53 PM] Command "/home/ondrej/.vscode-server/extensions/moetelo.twiggy-0.18.0/dist/phpUtils/printCraftTwigEnvironment.php /home/ondrej/webtest" failed with following message:
[Error - 8:31:53 PM] stdout:

undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Ti.callJson (/home/ondrej/.vscode-server/extensions/moetelo.twiggy-0.18.0/dist/server.js:131:77)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #t (/home/ondrej/.vscode-server/extensions/moetelo.twiggy-0.18.0/dist/server.js:127:6419)
    at async mr.refresh (/home/ondrej/.vscode-server/extensions/moetelo.twiggy-0.18.0/dist/server.js:127:6385)
    at async xi.onDidChangeConfiguration (/home/ondrej/.vscode-server/extensions/moetelo.twiggy-0.18.0/dist/server.js:132:1865)
```

I always used Craft in subfolder for separation. In folder above I have tools and in subfolder Craft.
I guess I can get it all in single folder, but it would be great if this worked.

I dont know about any workaround other than opening the Craft root folder. But wouldnt it be easiest to just add setting so user can select the Craft root folder manually?

Thanks.

**Comment by Gawel91** [comment]
@moetelo Looks like the extension is crashing. I made sure to have the latest version (0.19.1) and tried restarting it.

```
Node.js v20.19.0
[Error - 9:33:20 AM] Server process exited with code 1.
[Info  - 9:33:20 AM] Connection to server got closed. Server will restart.
true
node:events:502
      throw er; // Unhandled 'error' event
      ^

Error: spawn php ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn php',
  path: 'php',
  spawnargs: [
    '/Users/xxxxx/.vscode/extensions/moetelo.twiggy-0.19.1/dist/phpUtils/printCraftTwigEnvironment.php',
    '/Users/xxxxx/Workspace/qcq-base-craft'
  ]
}

Node.js v20.19.0
[Error - 9:33:20 AM] Server process exited with code 1.
[Error - 9:33:20 AM] The Twiggy Language Server file:///Users/xxxxx/Workspace/qcq-base-craft server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by moetelo** [comment]
@Gawel91 Do you have a `php` in your `PATH`? As far as I know, ENOENT means it can't spawn a php process. Try setting [twiggy.phpExecutable](https://github.com/moetelo/twiggy/blob/c65e81f235bf08bcefb62260cb14baaea5b39a68/packages/vscode/package.json#L63C10-L63C30) to a full php executable path
